### ISSUE TITLE
Link vscode extension in kedro docs and website

### ISSUE THREAD

**Issue by noklam** [kedro-org/vscode-kedro#11]
- [x] https://github.com/kedro-org/kedro-website/issues/190
- [ ] https://github.com/kedro-org/kedro/pull/3898

**Comment by noklam** [comment]
Opened a new one for kedro-website: https://github.com/kedro-org/kedro-website/issues/190
A PR on kedro: https://github.com/kedro-org/kedro/pull/3898

**Comment by noklam** [comment]
The PR in kedro's repo is now merged. There is already a separate issue for kedro-website, can this issue be closed?

**Comment by astrojuanlu** [comment]
Both PRs have been merged indeed, closing!
