### ISSUE TITLE
Better detection of when not working in a non-kedro project

### ISSUE THREAD

**Issue by datajoely** [kedro-org/vscode-kedro#137]
## Description
Starting vscode for something that is not a Kedro project does two things:

1. You get a bunch of error messages like:
![image](https://github.com/user-attachments/assets/e1ea2013-b2a0-4059-b1f5-b17bb088cc4d)

2.The `env` selector is present when it's not relevant. 
<img width="200" alt="image" src="https://github.com/user-attachments/assets/6929b54c-c3c9-405b-adc6-7ddc4c125705">

I think we should do a better job of conditionally disabling the extension when you're not working in a Kedro project. I fear these alerts may cause someone to uninstall the extension because they're being annoyed by notifications if Kedro is only a small part of their work day.

**Comment by noklam** [comment]
Same issue as #77 ?

**Comment by datajoely** [comment]
Yes we should close in favour of #77 I'll move my reply to your point above there.

**Comment by datajoely** [comment]
I want to reiterate I think there is a substantial risks users uninstall the extension because it's noisy and distracts you when you're working on something else. I've been working in FastAPI for the last week and I close the pop up every time I open the IDE.
