### ISSUE TITLE
Spike: How much of the extension is broken if it support 0.17+/0.18+

### ISSUE THREAD

**Issue by noklam** [kedro-org/vscode-kedro#48]
The original plan to support 0.19+ is a MVP solution. It assumes `OmegaConfigLoader` and `OmegaConfigLoader` is the only configloader for 0.19.  This has limited the extension for 0.19 only user.

# Background
0.19 is released in 2023 Dec, the adoption has been relatively slow (as Kedro project tend to last quite long and team rarely upgrade the library version unless there are some necessary change). The adoption is ~30%

![image](https://github.com/user-attachments/assets/dc4b5262-b41d-482b-968b-f99638769a9b)

# Context
OmegaConfigLoader is actually introduced in 0.18 earlier (forgot the exact version, probably mature around 0.18.12+). If we look into the stat, 0.18.14 alone has ~40% of Kedro user. This mean that we can actually support this group of user already.

![image](https://github.com/user-attachments/assets/3f156b23-e4ef-4b04-9f57-a25d910bc214)

Further pushing the idea, we can support non-OmegaConfigLoader user (or even 0.17+). Until today we haven't introduced any specific OmegaConfigLoader feature, [Add navigation support for OmegaConfig Syntax](https://github.com/kedro-org/vscode-kedro/issues/8). So it could be relatively easy to support older version of Kedro. Even if there are omegaconfig specific feature, it only affect some advance feature of code navigation (i.e. pipeline.py -> parameters.yml). Other feature such as:
- hover
- top-level pipeline.py -> config /  config -> pipeline.py shouldn't be affected.

The exact impact is unclear, and thus this ticket is about doing a spike to map this out.

cc @astrojuanlu

**Comment by merelcht** [comment]
Or we can use `kedro-vscode` to convince more people to upgrade to Kedro `0.19.+` because it doesn't support older versions.

**Comment by astrojuanlu** [comment]
As much as I'd like more people to use the extension, it's probably a lot of effort for us to support and as @merelcht says, the fact that only Kedro 0.19+ is supported could be a nice incentive to upgrade.

**Comment by datajoely** [comment]
I think it's a good thing to reserve important new user-facing features for later versions of Kedro. In the past we've been guilty of issuing breaking changes with very little incentives for people to migrate.

**Comment by noklam** [comment]
I understand the argument here, but I think 

> As much as I'd like more people to use the extension, it's probably a lot of effort for us to support 

The intuition here is actually opposite, it may be easy to add support for older versions without much effort.

>  could be a nice incentive to upgrade.

There could be still incentive to upgrade i.e. feature parity if we starting to implement things like https://github.com/kedro-org/vscode-kedro/issues/8, so only `OmegaConfigLoader` user get accurate navigation while others get some basic feature only.

> Or we can use kedro-vscode to convince more people to upgrade to Kedro 0.19.+ because it doesn't support older versions.

I am not a big fan of keeping feature just to force people to upgrade, our versioning strategy is usually around breaking changes/non-breaking, we didn't do this for `OmegaConfigLoader`.

With that said, I don't plan to do this before the marketing effort (Youtube, Linkedin post) go out. It's ideal if this actually drive more 0.19 adoption.

**Comment by noklam** [comment]
For the record, I did a quick test on 0.18.14 + OmegaConfigLoader. The only breaking changes are `_data_sets` -> `_dataset`. When running in debug mode the `hover` and `go to defintion` function are running just fine, except I get a weird server pannic that kills the server without any log.

**Comment by datajoely** [comment]
We could do something like "partial 0.18.x" support and not invest in edge cases which crop up

**Comment by astrojuanlu** [comment]
My recommendation would be to try to find Kedro 0.19+ projects that break the extension (I already found a few), try to focus on those, and when (1) the plugin is more solid, (2) there's more awareness, and (3) users pressure us to add support for older versions, we evaluate the effort

**Comment by noklam** [comment]
> My recommendation would be to try to find Kedro 0.19+ projects that break the extension (I already found a few)

Can you help to report those cases?

**Comment by astrojuanlu** [comment]
Surely 😄

**Comment by noklam** [comment]
Maybe the extension helps adoption some how, after 2 months the adoption of 0.19 is >50%

![image](https://github.com/user-attachments/assets/adb9a425-0daa-47c5-b46b-93239d54ef59)

I will close this issue as I think the benefit of supporting older versions make less sense now.
